<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <TModLoaderDirectory>$(MSBuildProjectDirectory)/../../.tools/tModLoader</TModLoaderDirectory>
    <BuildMod>false</BuildMod>
  </PropertyGroup>
  <Import Project="$(TModLoaderDirectory)/tMLMod.targets" />
  <ItemGroup>
    <Reference Include="Riakawa" HintPath="../../Riakawa/bin/Debug/net8.0/Riakawa.dll" Private="false" />
  </ItemGroup>
</Project>
